### ISSUE TITLE
[color scheme] proftpd

### ISSUE THREAD

**Issue by CWempe** [folkertvanheusden/multitail#16]
Three years ago I created a color scheme for proftpd logs.

https://github.com/CWempe/multitail-scheme-proftpd

![image](https://user-images.githubusercontent.com/1270359/204099719-5e2f02b6-03b5-4593-bee3-789549696ae9.png)

* for transfers bigger than 100 MB or longer than 5 minutes the numbers are highlighted red instead of green
* the last field (in/comlete) is also highlighted red or green
* same with the direction of transfers (**i**n/**o**ut)
* Colors could be choosen better, I guess

I am not sure if this is of interesst for anybody.
If so i could create a PR.

But feel free to take this and improve this.

**Comment by folkertvanheusden** [comment]
Yes, please make a PR!
