### ISSUE TITLE
[feature request] add an argument to prepend filename to each log line

### ISSUE THREAD

**Issue by yjqg6666** [folkertvanheusden/multitail#2]
$ multitail -w -D -ts -Q 1 "/var/log/app-*.log"
The output log source can not be identified. The use cases is grab all the file logs to console and piped to EFK system.

**Comment by folkertvanheusden** [comment]
Would "--label" work?

**Comment by yjqg6666** [comment]
> Would "--label" work?

--label '%filename' ? There do need a placeholder which would be replaced by the actual filename where the log message comes from.

**Comment by folkertvanheusden** [comment]
Can you please try 71eb056e0a52d0c7c1a119c8112ca134ec3a80de? That's the latest version.
It allows you to do e.g.:

multitail --label 'my label %f: ' /var/log/all

**Comment by yjqg6666** [comment]
@folkertvanheusden Thanks for your instant help. But I got some tiny issue, only the first file got labeled.

```bash
$ ls /tmp/logs
t1.log  t2.log

$./multitail --label 'file %f:' /tmp/logs/t*.log
```
### Screenshot
![image](https://user-images.githubusercontent.com/1879641/180396838-fa51f57b-002a-40d7-aec0-d90e6b88f450.png)

And no effect on "-Q 1 file_name_pattern".
```shell
$./multitail --label 'file %f:' -Q 1 '/tmp/logs/t*.log'
```
### Screenshot
![image](https://user-images.githubusercontent.com/1879641/180397725-ef71491d-7940-409b-9518-ea3c01bdb179.png)

**Comment by folkertvanheusden** [comment]
f5210fc4686e5ec89178f127c7c9e851e0aa3cad should work, labels previously did not work at all for -Q.

**Comment by yjqg6666** [comment]
@folkertvanheusden The second use case (-Q) is checked and it's working. Thanks a lot for the support.

The first one '--lable "%f" /tmp/logs/*.log'  when multiple files are monitored, only the first window works.
```shell
$ ./bin/multitail --label '%f:' /tmp/logs/*.log
```
![image](https://user-images.githubusercontent.com/1879641/180679715-9aac3cd4-c7f4-472c-9ece-77fbc678a905.png)

**Comment by folkertvanheusden** [comment]
Hi,

I've added "--all-label" for that now.

**Comment by yjqg6666** [comment]
Thanks a lot. Now both are working like a charm.
