### ISSUE TITLE
v7.1.1 segfaults on macOS

### ISSUE THREAD

**Issue by p-linnane** [folkertvanheusden/multitail#21]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v7.1.1 of multitail, we ran into an issue where the resulting binary segfaults. To build we run `make -f makefile.macosx multitail DESTDIR=#{HOMEBREW_PREFIX}`.

Relates to https://github.com/Homebrew/homebrew-core/pull/152509

**Comment by folkertvanheusden** [comment]
Can you generate a stacktrace? In a debug build preferably

Op do 26 okt. 2023 23:07 schreef Patrick Linnane ***@***.***>:

**Comment by p-linnane** [comment]
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x40)
    frame #0: 0x000000018d247600 libsystem_pthread.dylib`pthread_mutex_lock + 12
libsystem_pthread.dylib`pthread_mutex_lock:
->  0x18d247600 <+12>: ldr    x8, [x0]
    0x18d247604 <+16>: mov    w9, #0x545a
    0x18d247608 <+20>: movk   w9, #0x4d55, lsl #16
    0x18d24760c <+24>: cmp    x8, x9
```

**Comment by folkertvanheusden** [comment]
This can't be right: multitail does not use pthreads.

**Comment by p-linnane** [comment]
I'm not sure. This is using `lldb`.

```
╰─ lldb multitail
(lldb) target create "multitail"
Current executable set to '/opt/homebrew/bin/multitail' (arm64).
(lldb) run
Process 85593 launched: '/opt/homebrew/bin/multitail' (arm64)
Process 85593 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x40)
    frame #0: 0x000000018d247600 libsystem_pthread.dylib`pthread_mutex_lock + 12
libsystem_pthread.dylib`pthread_mutex_lock:
->  0x18d247600 <+12>: ldr    x8, [x0]
    0x18d247604 <+16>: mov    w9, #0x545a
    0x18d247608 <+20>: movk   w9, #0x4d55, lsl #16
    0x18d24760c <+24>: cmp    x8, x9
Target 0: (multitail) stopped.
````

**Comment by folkertvanheusden** [comment]
Can't reproduce it under Linux. I'll see if I can borrow a mac.

**Comment by chenrui333** [comment]
you can try this workflow https://github.com/chenrui333/github-action-test/blob/main/.github/workflows/brew-debug.yml and tmate to use macos github action runner to do the debugging (running brew installation in the runner)

**Comment by folkertvanheusden** [comment]
Thanks for the suggestion but I don't want to learn a tool only for
debugging multitail on a Mac.
This weekend I fetched the mac at my parent's house. Now installing brew on
it. Takes a bit because the mac is from 2009 and has no SSD :-)

**Comment by folkertvanheusden** [comment]
The segfault is confirmed: I can reproduce it here. Multitail does not
start at all on this mac.

**Comment by folkertvanheusden** [comment]
solved in 7.1.2
I did a closedir on a nullptr

**Comment by p-linnane** [comment]
Thank you. I will run it through our CI once you tag it.

**Comment by folkertvanheusden** [comment]
done

**Comment by p-linnane** [comment]
Thank you very much for the help!
