### ISSUE TITLE
Coloring honeypots logs

### ISSUE THREAD

**Issue by Firzum** [folkertvanheusden/multitail#4]
Hello,

Please find a proposal for honeypots project log coloring/

```
# Honeypots https://github.com/qeeqbox/honeypots
colorscheme:honey:honeypots logs https://github.com/qeeqbox/honeypots
cs_re_s:green:"action": "(process)"
cs_re_s:yellow,,bold:"action": "([^"]+)"
cs_re_s:blue,,bold:"dest_port": "([0-9]+)"
cs_re_s:blue,,bold:"server": "([^"]+)"
cs_re_s:magenta,,bold:"src_ip": "([^"]+)"
cs_re:red:error
cs_re_s:red,,bold:"error": "([^"]+)"
cs_re_s:white,cyan,bold:"uri": "([^"]+)"

```
Result:

![image](https://user-images.githubusercontent.com/4751946/190673111-eff931e0-e15a-4fa2-aac5-affc5c823b34.png)

Hope this helps,

Regards

**Comment by folkertvanheusden** [comment]
Hi,

Thanks for the colorings!
Would it be possible to do all the magic of git pull edit and making a pull
request? Or shall I just copy/paste it myself?

**Comment by Firzum** [comment]
Oh, you are so right, I never did it but I'll give it a try.

**Comment by Firzum** [comment]
Created a pull request
