### ISSUE TITLE
Lookahead not working in Regex?

### ISSUE THREAD

**Issue by BenjaminDaSilva** [folkertvanheusden/multitail#9]
It seems (negative) lookahead isn't working in RegEx:

```
[root@myMachine]# multitail -E '^(?!.*AUTH).*$' access_log_.txt
 --*- multitail 6.5.0 (C) 2003-2019 by folkert@vanheusden.com -*--

The following problem occured:
-----------------------------
Failed to compile regular expression '^(?!.*AUTH).*$'.
Reason: MultiTail warning: regular expression failed, reason: Invalid preceding regular expression
```

**Comment by folkertvanheusden** [comment]
MultiTail uses "POSIX Extended Regular Expression syntax", is that the
problem?

**Comment by BenjaminDaSilva** [comment]
Well, I guess that's the issue then ...
_"[POSIX extended regular expressions do not support negative lookahead assertions.](https://stackoverflow.com/a/55190898)"_

I'll try to find a work around ....
